module.exports = {
    /*
    ESTA CONSULTA, RETORNA UNA LISTA DE LAS NO-CATEGORIAS DE UN LIBRO,
    LA CUAL SERA UTILIZADA EN EL FORMULARIO DE EDICION (DEL LIBRO)
    PARA COMPLETAR LA LISTA DE OPCIONES DE CATEGORIAS QUE SE CONSTRUYE 
    A PARTIR DE LA CATEGORIA DEL LIBRO Y AQUELLAS A LAS QUE NO PERTENECE EL MISMO,
    PERMITIENDO QUE LA LISTA DE OPCIONES NO TENGA CATEGORIAS DUPLICADAS 
    */
    categorias: (categoria_id) => {
        return `SELECT categoria.id as categoria_id, categoria.categoria FROM categoria WHERE 1 AND categoria.id NOT in (${categoria_id});`
    }
}